# Generated by Django 5.0.6 on 2024-05-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_comment_commentator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentator',
            new_name='commentor',
        ),
    ]
