# Generated by Django 5.0.6 on 2024-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_commentator_comment_commentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.CharField(max_length=10),
        ),
    ]
